#!/bin/bash

[[ $# -lt 4 ]] && exit 1
tty="$1"
baud="$2"
group="$3"
device="$4"

udevice="$tty"
stty -F $udevice speed 115200 cs8 echonl -cstopb -parenb -parodd -hupcl cread clocal -crtscts -ignbrk brkint ignpar -parmrk -inpck -istrip -inlcr -igncr -icrnl ixon -ixoff -iuclc -ixany -imaxbel -iutf8 -opost -olcuc -ocrnl -onlcr -onocr -onlret -ofill -ofdel nl0 cr0 tab0 bs0 vt0 ff0 -isig -icanon iexten -echo echoe echok -noflsh -xcase -tostop -echoprt echoctl echoke

# reboot router
for ((i=0;i<5;i++))
do
sudo /usr/bin/send $group $device 0
sleep 1
done
sleep 10
echo exit > $udevice
echo exit > $udevice
echo exit > $udevice
cat $udevice &
cc=$!
for ((i=0;i<5;i++))
do
sudo /usr/bin/send $group $device 1
sleep 1
done
sleep 60
echo "" >$udevice
echo "logread" > $udevice
sleep 5
echo "ps w" > $udevice
sleep 5
echo "batctl o ">$udevice
sleep 5
kill $cc

