#!/bin/bash
# set -ix
sudo iw dev wlan0 connect $1 2412
time sudo dhclient wlan0
err=$?
sudo ifconfig wlan0
sudo ifconfig wlan0 down
#sudo ping 10.126.0.1
#sudo ping 10.126.0.2
#sudo ip rule del to 212.227.222.9; sudo ip rule add to 212.227.222.9 lookup fftest
#sudo ip rule del to 212.227.222.8; sudo ip rule add to 212.227.222.8 lookup fftest
#ip route flush table fftest
#ip route add 0.0.0.0 via 10.126.8.1
#ip route add 0.0.0.0 via 10.126.16.1
#sudo ping -I wlan0 212.227.222.9

#wget -q -O - http://www.web.de
exit $err

